version: '3.4'

services:
  php:
    build:
      context: .docker/
    env_file:
      - .docker/php.env
    volumes:
      - ./app/:/var/www/app
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf.d/20-overrides.ini:/usr/local/etc/php/conf.d/20-overrides.ini
    depends_on:
      - db

  db:
    image: library/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .docker/mysql.env
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    image: nginx:1.19-alpine
    volumes:
      - ./app/webroot:/var/www/app/webroot
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
volumes:
  data: