version: '3.4'

services:
  php:
    build:
      context: .docker/
    environment:
      PHP_IDE_CONFIG: 'serverName=localhost'
    volumes:
      - ./app/:/var/www/app
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf.d/20-overrides.ini:/usr/local/etc/php/conf.d/20-overrides.ini
    depends_on:
      - db

  db:
    image: library/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?Missing MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?Missing MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER:?Missing MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?Missing MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    image: nginx:1.19-alpine
    volumes:
      - ./app/webroot:/var/www/app/webroot
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
volumes:
  data: