name: Build

on: [pull_request]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Env Files
        run: |
          cp .docker/php.env.development .docker/php.env
          cp .docker/mysql.env.development .docker/mysql.env
      - name: Pull images
        run: docker-compose -f .docker/docker-compose.yml pull
      - name: Build
        run: docker-compose -f .docker/docker-compose.yml build --build-arg ENVIRONMENT=dev --build-arg USER_ID=$(id) --build-arg USERNAME=cakephp --build-arg APP_DIR=app
      - name: Start
        run: docker-compose -f .docker/docker-compose.yml
      - name: Wait for services
        run: sleep 5
      - name: HTTP Check
        run: curl -v -o /dev/null http://localhost:8080
      - name: MySQL Check
        run: mysql -u root -h 0.0.0.0 -proot --port 3307 -e "status"
      - name: Composer Test
        run: docker exec $(docker-compose -f .docker/docker-compose.yml ps -q php) composer test
